overrides:
  twistingnether: twisting-nether
  twisting-nether: twisting-nether
  defiasbrotherhood: defias-brotherhood
  defias-brotherhood: defias-brotherhood
  argentdawn: argent-dawn
  argent-dawn: argent-dawn
